# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bowline-bundler}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.5") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex MacCaw"]
  s.date = %q{2010-05-27}
  s.default_executable = %q{bowline-bundle}
  s.email = %q{alex@leadthinking.com}
  s.executables = ["bowline-bundle"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/bowline-bundle",
     "lib/bowline/bundler.rb",
     "lib/bowline/bundler/bundle.rb",
     "lib/bowline/bundler/cli.rb",
     "lib/bowline/bundler/dependency.rb",
     "lib/bowline/bundler/dsl.rb",
     "lib/bowline/bundler/environment.rb",
     "lib/bowline/bundler/finder.rb",
     "lib/bowline/bundler/gem_bundle.rb",
     "lib/bowline/bundler/gem_ext.rb",
     "lib/bowline/bundler/remote_specification.rb",
     "lib/bowline/bundler/resolver.rb",
     "lib/bowline/bundler/runtime.rb",
     "lib/bowline/bundler/source.rb",
     "lib/bowline/bundler/templates/app_script.erb",
     "lib/bowline/bundler/templates/environment.erb",
     "lib/bowline/bundler/templates/environment_picker.erb",
     "spec/bundler/cli_spec.rb",
     "spec/bundler/directory_spec.rb",
     "spec/bundler/dsl_spec.rb",
     "spec/bundler/fetcher_spec.rb",
     "spec/bundler/git_spec.rb",
     "spec/bundler/installer_spec.rb",
     "spec/bundler/manifest_file_spec.rb",
     "spec/bundler/manifest_spec.rb",
     "spec/bundler/runtime_spec.rb",
     "spec/bundler/system_gems_spec.rb",
     "spec/quality_spec.rb",
     "spec/resolver/engine_spec.rb",
     "spec/resolver/error_spec.rb",
     "spec/resolver/fake_source_index_spec.rb",
     "spec/resolver/prerelease_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/builders.rb",
     "spec/support/core_ext.rb",
     "spec/support/helpers.rb",
     "spec/support/matchers.rb",
     "spec/support/path_utils.rb"
  ]
  s.homepage = %q{http://github.com/maccman/bowline-bundler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An easy way to vendor gem dependencies for Bowline apps}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

